### PR TITLE
Install Git. Git is found in most official and unofficial Docker stacks.

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by ndarilek** [comment]
Any updates on this? I'd like to use this image since it's the closest thing to an official Meteor stack, but it really needs to ship Git as most of the existing stack images do. I'd also like to submit other PRs for handling things like settings, and am using this one to gauge how well such things will be received.

Thanks.

**Comment by arunoda** [comment]
Could you tell me why you need git? A lot of official repo are too big. We don't need to be too big.

**Comment by ndarilek** [comment]
Checking out NPM modules, pulling in submodules as part of a build. Lots 
of standard tooling expects Git, and functionality is diminished if it 
isn't present.

**Comment by arunoda** [comment]
Okay. I like it.

**Comment by jshimko** [comment]
On a related note, what do you guys think about adding the ability to build from a git repo like [ulexus/meteor](https://hub.docker.com/r/ulexus/meteor/) does?  Seems like that could be really useful for certain types of build automation, etc.

Thoughts?

**Comment by arunoda** [comment]
I think we will stay with the current way. In most of the CI environments, we've git. 
So, it's fair to use that way.

**Pull request merged**
