### PR TITLE
Respecting port env variable. Defaulting to port 80.

### LINKED ISSUE #23: Dont hard code port 80
I want to run the app on port 3000. As far as I can see the environment variable "PORT" will not be respected. I would love to be able to set 

``` bash
-e PORT=3000
```

What do you say?

### PR DESCRIPTION
**Pull request by levino**
Fixes #23

### CODE REVIEW

**Comment by levino** [comment]
Can this be closed and shipped? I kinda have to workaround a lot for the time being. Would love to be able to use the image from dockerhub again.

**Comment by lieuwex** [comment]
:+1:

**Comment by dragn** [comment]
+1 this PR is super needed.

**Comment by arunoda** [comment]
Thanks. Got a similar PR like this.

**Pull request closed without merging**
