### PR TITLE
Install meteor before copying app content

### PR DESCRIPTION
**Pull request by pauloborges**
This PR modifies Dockerfile to install meteor before copying app content to leverage image cache.

With this modification, one doesn't need to re-download meteor everytime he builds a new app image after modify his code.

### CODE REVIEW

**Comment by arunoda** [comment]
Did you test this? I wonder how this works.
This is a onbuild command and Meteor binary gets removed after the image build.

**Comment by pauloborges** [comment]
Yes, I tested it.

The image build process builds intermediates images for each `Dockerfile` instruction. When you ask docker to build the same image, it will reuse unchanged intermediate images from non changed instructions. You can also tell docker to not use cache using `docker build --no-cache ...`.

Read more here: https://docs.docker.com/articles/dockerfile_best-practices/#build-cache

**Comment by arunoda** [comment]
Okay. Got it.

**Comment by arunoda** [comment]
Thanks. This will get build now and will be available on the registry.
see: https://registry.hub.docker.com/u/meteorhacks/meteord/build_id/39804/code/bpvnd37s46ddkgrdf2tp2bn/

**Pull request merged**
