### PR TITLE
Update docker-compose.yml in readme

### PR DESCRIPTION
**Pull request by benjick**
That old mongo image is missing.

No point in exposing mongo ports when we are linking.

### CODE REVIEW

**Comment by benjick** [comment]
bump

**Comment by jshimko** [comment]
Or even better, use the official mongo release!

``` yaml
myapp:
  image: myname/myapp:latest
  links:
    - mongo
  ports:
    - "80:80"
  environment:
    ROOT_URL: "http://example.com"
    MONGO_URL: "mongodb://mongo:27017/myapp"

mongo:
  image: mongo:latest
  command: mongod --smallfiles --storageEngine=wiredTiger
```

(assuming you set the app image on line 2 to your app container, this config will work as-is)

**Comment by jshimko** [comment]
Sorry, just noticing that's exactly what you changed it to.  My bad.  :)

**Comment by jshimko** [comment]
I also don't see the point of changing the Node port to 3000 and then exposing 80 on the container.  Why not just leave it at the default of 80 and expose it on the same port (`80:80`)?  And the delay of 30 secs isn't necessary in my experience.  I use meteord for every meteor app I build and I've never needed to add a delay when using docker-compose.  So that's a few more lines that could be removed.  The readme example could be simplified to...

``` yaml
dashboard:
  image: yourrepo/yourapp
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/yourapp
   - ROOT_URL=http://yourapp.com
   - MAIL_URL=smtp://some.mailserver.com:25

mongo:
  image: mongo:latest
```

Or if you want to pass some mongo options...

``` yaml
dashboard:
  image: yourrepo/yourapp
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/yourapp
   - ROOT_URL=http://yourapp.com
   - MAIL_URL=smtp://some.mailserver.com:25

mongo:
  image: mongo:latest
  command: mongod --smallfiles --storageEngine=wiredTiger
```

**Comment by arunoda** [comment]
Yep. I'll update the README with this one:

```
dashboard:
  image: yourrepo/yourapp
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/yourapp
   - ROOT_URL=http://yourapp.com
   - MAIL_URL=smtp://some.mailserver.com:25

mongo:
  image: mongo:latest
```

**Comment by benjick** [comment]
Nice!

**Pull request closed without merging**
