### PR TITLE
Do npm install in our application before building

### PR DESCRIPTION
**Pull request by mitjajez**
We need to install node_modules of our app. We usualy remove it from source with .gitignore

### CODE REVIEW

**Comment by mbeynon** [comment]
What's the status of including this fix?  Without it, my builds fail on missing npm dependencies that "npm install' will fix.  Meteor 1.3 best practices in the guide suggests `npm install` prior to `meteor build`.  I don't see a clean workaround.

**Comment by jshimko** [comment]
This looks good to me.  You ok with merging @arunoda?

**Comment by mitjajez** [comment]
I saw on [meteor-buildpack-horse](https://github.com/AdmitHub/meteor-buildpack-horse/commit/1c1de57e9e9cf3861b9a5f3ff101e2bbc3b7d645) that
`npm i` for our node_modules_ should be without `--production`,
but the last `npm i` - for meteor - should be --production

```
cd $BUNDLE_DIR/bundle/programs/server/
npm i --production
```

**Comment by tzapu** [comment]
any news on merging this?

**Comment by jshimko** [comment]
For anyone that's still waiting for updates here, I recently released my own base image that I've been using for months.  Using it is pretty much exactly the same as MeteorD.  You're welcome to use that instead...

https://github.com/jshimko/meteor-launchpad  

I use it for a bunch of different Meteor projects, so it will definitely be actively maintained for the foreseeable future.

**Comment by tzapu** [comment]
thanks for this @jshimko 
i have tried using your image with meteor-up, dev version, by specifying `dockerImage: 'jshimko/meteor-launchpad:latest'` and i ve gotten further than i ve ever gotten until now with deploying a 1.3.4 meteor app, but i still run into errors. maybe you have some idea

```
Recv failure: Connection reset by peer
    /opt/build_scripts/entrypoint.sh: line 14: cd: /opt/app: No such file or directory
    /opt/build_scripts/entrypoint.sh: line 14: cd: /opt/app: No such file or directory
    /opt/build_scripts/entrypoint.sh: line 14: cd: /opt/app: No such file or directory
    /opt/build_scripts/entrypoint.sh: line 14: cd: /opt/app: No such file or directory
    /opt/build_scripts/entrypoint.sh: line 14: cd: /opt/app: No such file or directory
    /opt/build_scripts/entrypoint.sh: line 14: cd: /opt/app: No such file or directory
```

this is where i ve gotten to now. i have modified my mup app name to be app, but no go.

this docker thing has me completly confused...

**Comment by mitjajez** [comment]
@tzapu please, report this bug on @jshimko's repo issues, not here.

**Pull request closed without merging**
